### ISSUE TITLE
Original download corrupted

### ISSUE THREAD

**Issue by felfert** [dittodhole/chocolatey-superorca#1]
Since some time, a checksum warning is produced when attemting to install superorca.
I downladed it manually from http://www.pantaray.com/SuperOrcaSetup.exe (the URL in chocolateyinstall.ps1)
and noticed that installation fails with a message "This app cannot run on your PC" so the
original download obviously appears to be corrupted. I contacted pantaray.com about that, but got
no response.

=> Since this is freeware anyway, I suggest to put the original binary into the assets subdir of this
repo and change the url in chocolateyinstall.ps1 accordingly.

Would you accept a PR regarding this?

CU
 -Fritz

**Comment by dittodhole** [comment]
Hi there!

Ah shhhh ... Interesting enough that the vendor has broken the installer 😢 
The [original ORCA MSI from the legacy Developer Tools](https://docs.microsoft.com/en-us/windows/win32/msi/orca-exe) might be an option, though. There's a [package](https://community.chocolatey.org/packages/orca) available.

Embedding the .msi-file in the package might be a viable solution (I don't know about any offical policy regarding embedding installers), but I don't want to take on the responsibility to track binaries neither in github nor in the package (I created this repository to solely provide an "easy" way of bundling the official installer).

Yet, there's a solution: I can add you as a maintainer on [Chocolatey](https://community.chocolatey.org/packages/superorca) and you can push your own package.


Best
Andreas

**Comment by felfert** [comment]
Hi Andreas,

Thanks for the quick reply!

> Hi there!
> 
> Ah shhhh ... Interesting enough that the vendor has broken the installer cry The [original ORCA MSI from the legacy Developer Tools](https://docs.microsoft.com/en-us/windows/win32/msi/orca-exe) might be an option, though. There's a [package](https://community.chocolatey.org/packages/orca) available.

I know the MS orca, but for obvious reasons I'd prefer superorca.

> 
> Embedding the .msi-file in the package might be a viable solution (I don't know about any offical policy regarding embedding installers), but I don't want to take on the responsibility to track binaries neither in github nor in the package (I created this repository to solely provide an "easy" way of bundling the official installer).
>

Does it **really** get embedded in the packagage itself, if it is just in the assets subdir? I don't think so.
At least, the use of icon url in chocolateyinstall.ps1 suggests otherwise. Regarding tracking of binaries:
Since pantaray did not respond and the version/release date hasn't changed since almost 10 years now,
I'd assume that they don't care and there won't be any newer versions released ever.

If you still insist on keeping it out of this repo, another solution would be
to host it somewhere else (archive.org?). (For example, I found the old binary at software.heise.de).
 
> Yet, there's a solution: I can add you as a maintainer on [Chocolatey](https://community.chocolatey.org/packages/superorca) and you can push your own package.
>

Hmm, regarding chocolatey, I'm just a casual user and **not** familiar with publishing my own package. So I would
prefer a solution in this existing repo. This also has the advantage that nothing has to change at the user side
(still the same package name)

So what do you think?

> Best Andreas

Cheers
 -Fritz

**Comment by dittodhole** [comment]
> Does it **really** get embedded in the packagage itself, if it is just in the assets subdir? I don't think so. At least, the use of icon url in chocolateyinstall.ps1 suggests otherwise.

The icon is included in the package, as `IconUrl` got deprecated in .nuspec-format (see [link](https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl)), but [seems OK with Chocolatey](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0033).

The package would need to pack the .msi-file, if you don't want to download it (see [link](https://github.com/dittodhole/chocolatey-superorca/blob/master/tools/chocolateyinstall.ps1#L4)).

> If you still insist on keeping it out of this repo, another solution would be
to host it somewhere else (archive.org?). (For example, I found the old binary at software.heise.de).

Nice catch 👍  that would be another option - any chance to track down a valid url? I would be happy to update accordingly!

> Hmm, regarding chocolatey, I'm just a casual user and not familiar with publishing my own package. So I would
prefer a solution in this existing repo. This also has the advantage that nothing has to change at the user side
(still the same package name)

That's exactly what maintainers do: they can push new versions to existing packages, even if they host the package-source in a different github repository.
See documentation on [taking over maintenance](https://docs.chocolatey.org/en-us/community-repository/maintainers/package-maintainer-handover).


Best
Andreas

**Comment by felfert** [comment]
> Nice catch +1 that would be another option - any chance to track down a valid url? I would be happy to update accordingly!

Found one :-)

https://web.archive.org/web/20220317083536/http://www.pantaray.com/SuperOrcaSetup.exe

This is the last known good snapschot captured by archive.org's Wayback machine on 17.03.2022 at 08:35:36

Cheers
 -Fritz

**Comment by dittodhole** [comment]
Hi Fritz,

thanks for helping out!

Already pushed the new version to Chocolatey - awaiting approval.


Best
Andreas
