### ISSUE TITLE
Duplicates #1: Update Download location for correct installer

### ISSUE THREAD

**Issue by klou** [dittodhole/chocolatey-superorca#7]
Unfortunately, it looks like the 20220317 iteration from the Wayback machine then reverts to the 20220501, which is the same as the current (broken) download with an incorrect checksum.

Perhaps back it up even further?  https://web.archive.org/web/20210211234647/https://www.pantaray.com/SuperOrcaSetup.exe seems to work.

**Comment by dittodhole** [comment]
Hi, and thanks for reporting!

Currently I am not actively maintaining this repository - Do you care to create a PR to fix #1 ?


Best
Andreas

**Comment by dittodhole** [comment]
Sorry for the delay 🤔 
Just pushed a [new version](https://community.chocolatey.org/packages/superorca/11.0.0.2), awaiting approval.

**Comment by dittodhole** [comment]
Got approved.
Thanks for your PR!


Best
Andreas
